### ISSUE TITLE
Inspiration: Alternote for OS X

### ISSUE THREAD

**Issue by clauseggers** [aniket-deole/notes#22]
This alternative Evernote client for OS X might be of inspiration:
http://alternoteapp.com/

Pretty much exactly what I'm looking for, but for Gnome.

**Comment by aniket-deole** [comment]
This is awesome! I'll check it out.
Thanks :)

**Comment by aniket-deole** [comment]
I checked it out. The animations make it look a lot elegant.
I'm afraid I don't know how to implement animations in gtk. I searched, but all the examples are for gtk2. 
I want them as well, but its less priority as of now.

Plus, Alternote does not function without evernote, whereas this works fine, and is completely independent of any backend.

**Comment by clauseggers** [comment]
I'm not too worried about animations either. What I liked was the clean design (as opposed to the official Evernote application). I especially like the contextual pop-up menus instead of a classical tool/icon bar.

**Comment by aniket-deole** [comment]
Agreed. Maybe we can implement it (or maybe autohide style in the current position) in a later version.

**Comment by clauseggers** [comment]
Very best of luck to you. Many people are looking for a good Evernote client for GNU/Linux.
