### ISSUE TITLE
No way back once into the Evernote authorization pane

### ISSUE THREAD

**Issue by Ghatage** [aniket-deole/notes#23]
Also, 
#1 Need a different icon for authorization pane.
#2 Need to remove the message once authorized (unverified)

**Comment by aniket-deole** [comment]
Aah. This is if u don't have a valid account correct?

**Comment by Ghatage** [comment]
Yes and even if you don't have an account.
I just checked out the button right now and had no way to come back to the notes view

**Comment by aniket-deole** [comment]
Yes. Right now it assumes that it is a valid account.  I'll fix this today. Along with the minor points.
