### ISSUE TITLE
Notes should have a licence

### ISSUE THREAD

**Issue by quassy** [aniket-deole/notes#26]
I don't know if you want to actually want to open source it or not, but if you do you should choose a licence that suits you. A lot of other GTK+ developers have opted for GPL v3, some for GPL v2 and MIT/Apache.

**Comment by aniket-deole** [comment]
I had chosen the GNU Lesser General Public License version 2.1 when I started it. 
Almost all src files have the license header in them.

**Comment by quassy** [comment]
Oh okay. Would be more obvious (and I think "more legal") if you put a `LICENSE` in the root of the repo so people see it immediately (legal: also I think you have to ship a licence with your app).

**Comment by aniket-deole** [comment]
Yes. I would add the license file. 
Sure, you can use the screenshot!

**Comment by aniket-deole** [comment]
d4db1ce823986bc622bf175de9b57c7c309660e0

**Comment by quassy** [comment]
Thanks, [nice screenshot is now up](https://quassy.github.io/elementary-apps/Notes/).
