### ISSUE TITLE
libthrift.so problem

### ISSUE THREAD

**Issue by GrouchyGaijin** [aniket-deole/notes#36]
I am running Freya 32bit and get an error during make.  I followed the install instructions at http://aniket-deole.github.io/notes/

`/usr/bin/ld: skipping incompatible /home/john/notes/src/libevernote/libthrift.so when searching for -lthrift
/usr/bin/ld: cannot find -lthrift
collect2: error: ld returned 1 exit status
make: *** [libevernote.so] Error 1
`

**Comment by aniket-deole** [comment]
The library that is there is precompiled for 64bit. 
You will have to compile libthrift manually for 32bits and use it.
